<?php

namespace App\Http\Controllers;

use App\Models\Analysis;
use App\Models\ChatMessage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Validator;

class AiController extends Controller
{
    protected $aiService;

    public function __construct(\App\Services\GeminiService $aiService)
    {
        $this->aiService = $aiService;
    }

    public function status()
    {
        return response()->json([
            'gemini_key_loaded' => $this->aiService->hasKey(),
            'demo_mode' => !$this->aiService->hasKey(),
            'api_connected' => true,
            'model' => 'gemini-1.5-flash'
        ]);
    }

    public function index(Request $request)
    {
        $analyses = Analysis::where('user_id', $request->user()->id)
            ->orderBy('created_at', 'desc')
            ->get();
        return response()->json($analyses);
    }

    public function analyze(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'photo' => 'required|image|mimes:jpeg,png,jpg,webp|max:5120',
                'pet_id' => 'nullable|integer'
            ]);

            if ($validator->fails()) {
                return response()->json(['errors' => $validator->errors()], 422);
            }

            // 1. Save photo locally
            $path = $request->file('photo')->store('analyses', 'public');
            $photoUrl = asset('storage/' . $path);

            $base64Image = base64_encode(file_get_contents($request->file('photo')->getRealPath()));
            $mimeType = $request->file('photo')->getClientMimeType();

            // 2. Call OpenAI Service
            $analysisResult = $this->aiService->analyzeImage($base64Image, $mimeType);

            // 3. Save to database
            $analysis = Analysis::create([
                'user_id' => $request->user()->id,
                'pet_id' => $request->filled('pet_id') ? intval($request->pet_id) : null,
                'photo' => $photoUrl,
                'animal_type' => $analysisResult['animal_type'],
                'breed' => $analysisResult['breed'],
                'confidence' => $analysisResult['confidence'],
                'age_estimation' => $analysisResult['age_estimation'],
                'weight_estimation' => $analysisResult['weight_estimation'],
                'personality_traits' => $analysisResult['personality_traits'],
                'behavior_analysis' => $analysisResult['behavior_analysis'],
                'health_observations' => $analysisResult['health_observations'],
                'nutrition_recommendations' => $analysisResult['nutrition_recommendations'],
            ]);

            // Attach a demo flag if it was generated by fallback
            $analysis->is_demo = $analysisResult['is_demo'] ?? false;

            return response()->json($analysis, 201);
        } catch (\Exception $e) {
            return response()->json([
                'error' => 'Une erreur inattendue est survenue lors de l\'analyse.',
                'message' => 'Veuillez réessayer plus tard.'
            ], 500);
        }
    }

    public function chatHistory(Request $request)
    {
        $messages = ChatMessage::where('user_id', $request->user()->id)
            ->orderBy('created_at', 'asc')
            ->get(['role as sender', 'content as text']);
            
        return response()->json($messages);
    }

    public function chat(Request $request)
    {
        try {
            $request->validate([
                'message' => 'required|string',
            ]);

            $user = $request->user();
            $userMessage = $request->message;

            // Fetch user's pets to provide context to AI
            $pets = \App\Models\Pet::where('user_id', $user->id)->get();

            // Save user message FIRST so it's in history
            ChatMessage::create([
                'user_id' => $user->id,
                'role' => 'user',
                'content' => $request->message
            ]);

            // Fetch recent history (including the one we just saved)
            $history = ChatMessage::where('user_id', $user->id)
                ->orderBy('created_at', 'asc')
                ->get(['role as sender', 'content as text'])
                ->toArray();

            // Pop the last message from history so we don't pass it twice to GeminiService
            $historyWithoutLast = array_slice($history, 0, -1);

            $reply = $this->aiService->chat($request->message, $historyWithoutLast, $pets);

            // Save AI response
            ChatMessage::create([
                'user_id' => $user->id,
                'role' => 'model',
                'content' => $reply
            ]);

            return response()->json([
                'reply' => $reply
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'error' => 'Erreur lors de la communication avec l\'assistant vétérinaire.',
                'message' => 'Veuillez réessayer.'
            ], 500);
        }
    }
}
